### ISSUE TITLE
刷新速度（

### ISSUE THREAD

**Issue by anyneko** [NitroRCr/OneTextJS#1]
默认刷新速度为15秒会导致一些问题。
实际上，不管是我自己的库还是官方的库，规模都不是很大，如果刷新速度太快会导致存储库很快出现重复。
~~ 实际上，如果所有调用的人都遵循最佳实践，那么这不会导致任何问题。不过（（（  ~~

**Comment by NitroRCr** [comment]
之前还是10秒，，只是为了感知更强和方便测试  
实际上，重复不算大问题，这个东西只是用来装饰页面的，没人盯着这个看半天。。。  
当然，时间还是可以调长点，然后再加个避免重复的机制？随机顺序遍历整个库，应该会好不少
