### ISSUE TITLE
新的存储库（来自第三方

### ISSUE THREAD

**Issue by anyneko** [NitroRCr/OneTextJS#2]
虽然官方存储库和我的库规模都很小，但是你可以考虑加入由[lz已经是条咸鱼了](https://github.com/XiaoMengXinX)所提供的第三方库，它号称有三千条句子，所以（你知道我要说什么吧
https://github.com/XiaoMengXinX/OneText-Library

**Comment by NitroRCr** [comment]
规模太大体积有点难搞。。。400多k。。。直接放到js不太好  
主要是js不能跨域，其实我最初就考虑过`ajax`加载  
我再想想别的办法

**Comment by NitroRCr** [comment]
加上了april，至于那三千条句子，我还是调用的Hitokoto的API，jsonp跨域
